version: 2

project_name: ktop

release:
  name_template: "Version {{.Version}}"
  github:
    owner: vladimirvivien
    name: ktop

before:
  hooks:
    - go mod tidy
builds:
  - id: ktop
    binary: ktop
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: riscv64
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/vladimirvivien/ktop/buildinfo.Version=v{{.Version}} -X github.com/vladimirvivien/ktop/buildinfo.GitSHA={{.FullCommit}}

  - id: kubectl-ktop
    binary: kubectl-ktop
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - riscv64
    goarm:
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: riscv64
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/vladimirvivien/ktop/buildinfo.Version=v{{.Version}} -X github.com/vladimirvivien/ktop/buildinfo.GitSHA={{.FullCommit}}

archives:
   - id: ktop
     builds:
     - ktop
     name_template: '{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
     wrap_in_directory: false
     format: tar.gz
     files:
     - LICENSE

   - id: kubectl-ktop
     builds:
     - kubectl-ktop
     name_template: '{{ .Binary }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
     wrap_in_directory: false
     format: tar.gz
     files:
       - LICENSE

checksum:
  name_template: 'checksums.txt'

# kubectl krew plugin
krews:
-
  ids:
    - kubectl-ktop
  name: ktop
  homepage: https://github.com/vladimirvivien/ktop
  description: |
    This is a kubectl plugin for ktop, a top-like tool for displaying workload
    metrics for a running Kubernetes cluster.
  short_description: A top tool for kubernetes to display workload metrics
  caveats: |
    * By default, ktop displays metrics for resources in the default namespace. You can override this behavior
    by providing a --namespace or use -A for all namespaces.
  skip_upload: true

# Homebrew
brews:
  - name: ktop
    ids:
    - ktop
    repository:
      owner: vladimirvivien
      name: homebrew-oss-tools
      branch: main
    commit_author:
      name: vladimirvivien
      email: vladimir.vivien@gmail.com
    homepage: https://github.com/vladimirvivien/ktop
    description: A top-like tool to display kubernetes workload metrics
    license: "Apache-2.0 license"
    skip_upload: auto

# ko-generated images

kos:
  - id: ko-ktop
    build: ktop
    repository: ghcr.io/vladimirvivien/ktop
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    platforms: 
    - linux/amd64
    - linux/arm64
    - linux/arm/v7
    - linux/riscv64